In [1]:
import pandas as pd
import re
from pathlib import Path

In [2]:
base_path = Path("../../../daos-benchmarking/ior_results")

def extract_segments(dir_name):
    m = re.search(r'seg-(\d+)', dir_name)
    return int(m.group(1)) if m else None

def extract_filename_meta(stem):
    """Extract nnodes, ppn, xfer_str from stems like write_n-8_ppn-16_tx-2M or rw_n-8_ppn-16_tx-2M."""
    m = re.match(r'^(?:write|rw|read)_n-(\d+)_ppn-(\d+)_tx-(\w+)$', stem)
    if m:
        return int(m.group(1)), int(m.group(2)), m.group(3)
    return None, None, None

records = []
skipped = []
errors  = []

for csv_file in sorted(base_path.rglob("*.csv")):
    # Skip root-level aggregate CSVs (ior_rw.csv, ior_all_results.csv, etc.)
    if csv_file.parent == base_path:
        continue

    rel_parts = csv_file.relative_to(base_path).parts
    category       = rel_parts[0]
    experiment_run = rel_parts[1] if len(rel_parts) > 2 else ""

    segments = extract_segments(experiment_run)
    nnodes, ppn, xfer_str = extract_filename_meta(csv_file.stem)

    if nnodes is None:
        skipped.append(str(csv_file.relative_to(base_path)))
        continue

    try:
        df = pd.read_csv(csv_file)
        if df.empty:
            errors.append(f"empty: {csv_file.relative_to(base_path)}")
            continue
    except Exception as e:
        errors.append(f"read error ({e}): {csv_file.relative_to(base_path)}")
        continue

    df["fromCSV"]         = csv_file.name
    df["source_category"] = category
    df["experiment_run"]  = experiment_run
    df["segments"]        = segments
    df["nnodes"]          = nnodes
    df["tasks_per_node"]  = ppn
    df["xfer_str"]        = xfer_str
    df["bw(GiB/s)"]       = df["bw(MiB/s)"] / 1024
    df["Latency(ms)"]     = df["Latency"] * 1000

    records.append(df)

all_df = pd.concat(records, ignore_index=True)

print(f"Total rows   : {len(all_df)}")
print(f"Source files : {all_df['fromCSV'].nunique()}")
if errors:
    print(f"\nWarnings ({len(errors)} files):")
    for e in errors:
        print(f"  {e}")
if skipped:
    print(f"\nSkipped — unrecognised name pattern ({len(skipped)} files):")
    for s in skipped:
        print(f"  {s}")

Total rows   : 4697
Source files : 449

Warnings (1 files):
  read error (No columns to parse from file): ior_results_archive/ior-results-rw_n-8_seg-32_20251006_11-39-32/rw_n-8_ppn-120_tx-2M.csv

Skipped — unrecognised name pattern (4 files):
  ior_results_archive/ior_results.csv
  ior_results_xmei/merged_ior_results_n-16_48core-skip1.csv
  ior_results_xmei/merged_ior_results_n-1_24core-skip4.csv
  ior_results_xmei/merged_ior_results_n-1_48core-skip1.csv

In [3]:
print("Rows per source_category:")
print(all_df["source_category"].value_counts().to_string())
print("\nRows per nnodes:")
print(all_df["nnodes"].value_counts().sort_index().to_string())
print("\nRows per xfer_str:")
print(all_df["xfer_str"].value_counts().sort_index().to_string())
print("\nRows per access:")
print(all_df["access"].value_counts().to_string())
all_df.head(10)

Rows per source_category:
source_category
ior_results_archive    1711
write_then_read        1196
ior_results_xmei       1190
write_only              600

Rows per nnodes:
nnodes
1     1685
2      460
4      460
8     1196
16     600
32     296

Rows per xfer_str:
xfer_str
16K    1075
16M    1070
1M     1071
2M     1061
8M      420

Rows per access:
access
write    3856
read      841

,access,bw(MiB/s),IOPS,Latency,block(KiB),xfer(KiB),open(s),wr/rd(s),close(s),total(s),...,iter,fromCSV,source_category,experiment_run,segments,nnodes,tasks_per_node,xfer_str,bw(GiB/s),Latency(ms)
0,write,11051.5793,707418.8816,0.0423,131072.0,16.0,0.1821,355.7415,15.3104,355.8007,...,0,rw_n-8_ppn-120_tx-16K.csv,ior_results_archive,ior-results-rw_n-8_seg-32_20251006_11-39-32,32,8,120,16K,10.792558,42.3
1,read,10040.5356,642599.4887,0.0476,131072.0,16.0,0.1018,391.6253,22.8077,391.6285,...,0,rw_n-8_ppn-120_tx-16K.csv,ior_results_archive,ior-results-rw_n-8_seg-32_20251006_11-39-32,32,8,120,16K,9.805211,47.6
2,write,11073.3765,708757.7958,0.0424,131072.0,16.0,0.1603,355.0694,14.8552,355.1004,...,1,rw_n-8_ppn-120_tx-16K.csv,ior_results_archive,ior-results-rw_n-8_seg-32_20251006_11-39-32,32,8,120,16K,10.813844,42.4
3,read,10033.3489,642139.4703,0.0468,131072.0,16.0,0.1132,391.9059,22.7446,391.9090,...,1,rw_n-8_ppn-120_tx-16K.csv,ior_results_archive,ior-results-rw_n-8_seg-32_20251006_11-39-32,32,8,120,16K,9.798192,46.8
4,write,11042.5184,706846.1071,0.0420,131072.0,16.0,0.1602,356.0297,15.3187,356.0927,...,2,rw_n-8_ppn-120_tx-16K.csv,ior_results_archive,ior-results-rw_n-8_seg-32_20251006_11-39-32,32,8,120,16K,10.783709,42.0
5,read,10029.3590,641884.1751,0.0468,131072.0,16.0,0.1314,392.0618,20.9410,392.0649,...,2,rw_n-8_ppn-120_tx-16K.csv,ior_results_archive,ior-results-rw_n-8_seg-32_20251006_11-39-32,32,8,120,16K,9.794296,46.8
6,write,11044.8422,706899.4420,0.0418,131072.0,16.0,0.1416,356.0029,15.4852,356.0178,...,3,rw_n-8_ppn-120_tx-16K.csv,ior_results_archive,ior-results-rw_n-8_seg-32_20251006_11-39-32,32,8,120,16K,10.785979,41.8
7,read,9992.1229,639500.9168,0.0468,131072.0,16.0,0.0991,393.5229,21.0925,393.5260,...,3,rw_n-8_ppn-120_tx-16K.csv,ior_results_archive,ior-results-rw_n-8_seg-32_20251006_11-39-32,32,8,120,16K,9.757933,46.8
8,write,11016.5124,705157.2537,0.0416,131072.0,16.0,0.1473,356.8824,15.7940,356.9333,...,4,rw_n-8_ppn-120_tx-16K.csv,ior_results_archive,ior-results-rw_n-8_seg-32_20251006_11-39-32,32,8,120,16K,10.758313,41.6
9,read,9950.2841,636823.0961,0.0464,131072.0,16.0,0.1392,395.1776,21.1633,395.1807,...,4,rw_n-8_ppn-120_tx-16K.csv,ior_results_archive,ior-results-rw_n-8_seg-32_20251006_11-39-32,32,8,120,16K,9.717074,46.4

In [4]:
output_csv = Path("ior_all_results.csv")
all_df.to_csv(output_csv)
print(f"Saved to : {output_csv.resolve()}")
print(f"Shape    : {all_df.shape}")
print(f"Columns  : {list(all_df.columns)}")

Saved to : /Users/xmei/Documents/LDRD/pdsw26_daos-bench-res/results/aurora/ior/ior_all_results.csv
Shape    : (4697, 21)
Columns  : ['access', 'bw(MiB/s)', 'IOPS', 'Latency', 'block(KiB)', 'xfer(KiB)', 'open(s)', 'wr/rd(s)', 'close(s)', 'total(s)', 'numTasks', 'iter', 'fromCSV', 'source_category', 'experiment_run', 'segments', 'nnodes', 'tasks_per_node', 'xfer_str', 'bw(GiB/s)', 'Latency(ms)']

In [5]:
# --- Config/run summary ---
# A "config"  = unique (nnodes, tasks_per_node, xfer_str, access, segments)
# A "run"     = unique experiment_run directory (one job submission)
# An "iter"   = one repetition within a run (iter 0–4)

config_cols = ["nnodes", "tasks_per_node", "xfer_str", "access", "segments"]

summary = (
    all_df.groupby(config_cols)
    .agg(
        n_runs=("experiment_run", "nunique"),
        n_iters=("iter", "count"),          # total rows = runs × iters_per_run
    )
    .reset_index()
    .sort_values(config_cols)
)

print(f"Unique configs : {len(summary)}")
print(f"Total rows     : {summary['n_iters'].sum()}")
print()
print(summary.to_string(index=False))

Unique configs : 553
Total rows     : 4697

 nnodes  tasks_per_node xfer_str access  segments  n_runs  n_iters
      1               6      16K   read        32       1        5
      1               6      16K  write        32       3       15
      1               6      16M   read        32       1        5
      1               6      16M  write        32       3       15
      1               6       1M   read        32       1        5
      1               6       1M  write        32       3       15
      1               6       2M   read        32       1        5
      1               6       2M  write        32       3       15
      1               6       8M  write        32       1        5
      1               8      16K   read        32       1        5
      1               8      16K  write         1       1        5
      1               8      16K  write         6       1        5
      1               8      16K  write        32       6       30
      1               8      16M   read        32       1        5
      1               8      16M  write         1       1        5
      1               8      16M  write         6       1        5
      1               8      16M  write        32       6       30
      1               8       1M   read        32       1        5
      1               8       1M  write         1       1        5
      1               8       1M  write         6       1        5
      1               8       1M  write        32       6       30
      1               8       2M   read        32       1        5
      1               8       2M  write         1       1        5
      1               8       2M  write         6       1        5
      1               8       2M  write        32       6       30
      1               8       8M  write        32       4       20
      1              12      16K  write         1       1        5
      1              12      16K  write         6       1        5
      1              12      16K  write        32       1        5
      1              12      16M  write         1       1        5
      1              12      16M  write         6       1        5
      1              12      16M  write        32       1        5
      1              12       1M  write         1       1        5
      1              12       1M  write         6       1        5
      1              12       1M  write        32       1        5
      1              12       2M  write         1       1        5
      1              12       2M  write         6       1        5
      1              12       2M  write        32       1        5
      1              12       8M  write        32       1        5
      1              16      16K   read        32       1        5
      1              16      16K  write        32       6       30
      1              16      16M   read        32       1        5
      1              16      16M  write        32       6       30
      1              16       1M   read        32       1        5
      1              16       1M  write        32       6       30
      1              16       2M   read        32       1        5
      1              16       2M  write        32       6       30
      1              16       8M  write        32       4       20
      1              24      16K  write         1       1        5
      1              24      16K  write         6       1        5
      1              24      16K  write        32       4       20
      1              24      16M  write         1       1        5
      1              24      16M  write         6       1        5
      1              24      16M  write        32       4       20
      1              24       1M  write         1       1        5
      1              24       1M  write         6       1        5
      1              24       1M  write        32       4       20
      1              24       2M  write         1       1        5
      1              24       2M  write         6       1        5
      1              24       2M  write        32       4       20
      1              24       8M  write        32       4       20
      1              32      16K   read        32       1        5
      1              32      16K  write         1       1        5
      1              32      16K  write         6       1        5
      1              32      16K  write        32       6       30
      1              32      16M   read        32       1        5
      1              32      16M  write         1       1        5
      1              32      16M  write         6       1        5
      1              32      16M  write        32       6       30
      1              32       1M   read        32       1        5
      1              32       1M  write         1       1        5
      1              32       1M  write         6       1        5
      1              32       1M  write        32       6       30
      1              32       2M   read        32       1        5
      1              32       2M  write         1       1        5
      1              32       2M  write         6       1        5
      1              32       2M  write        32       6       30
      1              32       8M  write        32       4       20
      1              40      16K  write        32       3       15
      1              40      16M  write        32       3       15
      1              40       1M  write        32       3       15
      1              40       2M  write        32       3       15
      1              40       8M  write        32       3       15
      1              48      16K   read        32       1        5
      1              48      16K  write         1       1        5
      1              48      16K  write         6       1        5
      1              48      16K  write        32       6       30
      1              48      16M   read        32       1        5
      1              48      16M  write         1       1        5
      1              48      16M  write         6       1        5
      1              48      16M  write        32       6       30
      1              48       1M   read        32       1        5
      1              48       1M  write         1       1        5
      1              48       1M  write         6       1        5
      1              48       1M  write        32       6       30
      1              48       2M   read        32       1        5
      1              48       2M  write         1       1        5
      1              48       2M  write         6       1        5
      1              48       2M  write        32       6       30
      1              48       8M  write        32       4       20
      1              56      16K  write        32       3       15
      1              56      16M  write        32       3       15
      1              56       1M  write        32       3       15
      1              56       2M  write        32       3       15
      1              56       8M  write        32       3       15
      1              64      16K  write        32       3       15
      1              64      16M  write        32       3       15
      1              64       1M  write        32       3       15
      1              64       2M  write        32       3       15
      1              64       8M  write        32       3       15
      1              72      16K  write        32       3       15
      1              72      16M  write        32       3       15
      1              72       1M  write        32       3       15
      1              72       2M  write        32       3       15
      1              72       8M  write        32       3       15
      1              80      16K  write        32       3       15
      1              80      16M  write        32       3       15
      1              80       1M  write        32       3       15
      1              80       2M  write        32       3       15
      1              80       8M  write        32       3       15
      1              88      16K  write        32       3       15
      1              88      16M  write        32       3       15
      1              88       1M  write        32       3       15
      1              88       2M  write        32       3       15
      1              88       8M  write        32       3       15
      1              96      16K  write         1       1        5
      1              96      16K  write         6       1        5
      1              96      16K  write        32       3       15
      1              96      16M  write         1       1        5
      1              96      16M  write         6       1        5
      1              96      16M  write        32       2       10
      1              96       1M  write         1       1        5
      1              96       1M  write         6       1        5
      1              96       1M  write        32       3       15
      1              96       2M  write         1       1        5
      1              96       2M  write         6       1        5
      1              96       2M  write        32       3       15
      1              96       8M  write        32       2       10
      1             108      16K  write         1       1        5
      1             108      16K  write         6       1        5
      1             108      16M  write         1       1        5
      1             108      16M  write         6       1        5
      1             108       1M  write         1       1        5
      1             108       1M  write         6       1        5
      1             108       2M  write         1       1        5
      1             108       2M  write         6       1        5
      1             128      16K  write         1       1        5
      1             128      16K  write         6       1        5
      1             128      16M  write         1       1        5
      1             128      16M  write         6       1        5
      1             128       1M  write         1       1        5
      1             128       1M  write         6       1        5
      1             128       2M  write         1       1        5
      1             128       2M  write         6       1        5
      2               6      16K   read        32       1        5
      2               6      16K  write        32       2       10
      2               6      16M   read        32       1        5
      2               6      16M  write        32       2       10
      2               6       1M   read        32       1        5
      2               6       1M  write        32       2       10
      2               6       2M   read        32       1        5
      2               6       2M  write        32       2       10
      2               8      16K   read        32       1        5
      2               8      16K  write         1       1        5
      2               8      16K  write        32       2       10
      2               8      16M   read        32       1        5
      2               8      16M  write         1       1        5
      2               8      16M  write        32       2       10
      2               8       1M   read        32       1        5
      2               8       1M  write         1       1        5
      2               8       1M  write        32       2       10
      2               8       2M   read        32       1        5
      2               8       2M  write         1       1        5
      2               8       2M  write        32       2       10
      2              12      16K  write         1       1        5
      2              12      16M  write         1       1        5
      2              12       1M  write         1       1        5
      2              12       2M  write         1       1        5
      2              16      16K   read        32       1        5
      2              16      16K  write        32       2       10
      2              16      16M   read        32       1        5
      2              16      16M  write        32       2       10
      2              16       1M   read        32       1        5
      2              16       1M  write        32       2       10
      2              16       2M   read        32       1        5
      2              16       2M  write        32       2       10
      2              24      16K  write         1       1        5
      2              24      16M  write         1       1        5
      2              24       1M  write         1       1        5
      2              24       2M  write         1       1        5
      2              32      16K   read        32       1        5
      2              32      16K  write         1       1        5
      2              32      16K  write        32       2       10
      2              32      16M   read        32       1        5
      2              32      16M  write         1       1        5
      2              32      16M  write        32       2       10
      2              32       1M   read        32       1        5
      2              32       1M  write         1       1        5
      2              32       1M  write        32       2       10
      2              32       2M   read        32       1        5
      2              32       2M  write         1       1        5
      2              32       2M  write        32       2       10
      2              48      16K   read        32       1        5
      2              48      16K  write         1       1        5
      2              48      16K  write        32       2       10
      2              48      16M   read        32       1        5
      2              48      16M  write         1       1        5
      2              48      16M  write        32       2       10
      2              48       1M   read        32       1        5
      2              48       1M  write         1       1        5
      2              48       1M  write        32       2       10
      2              48       2M   read        32       1        5
      2              48       2M  write         1       1        5
      2              48       2M  write        32       2       10
      2              96      16K  write         1       1        5
      2              96      16M  write         1       1        5
      2              96       1M  write         1       1        5
      2              96       2M  write         1       1        5
      2             108      16K  write         1       1        5
      2             108      16M  write         1       1        5
      2             108       1M  write         1       1        5
      2             108       2M  write         1       1        5
      2             128      16K  write         1       1        5
      2             128      16M  write         1       1        5
      2             128       1M  write         1       1        5
      2             128       2M  write         1       1        5
      4               6      16K   read        32       1        5
      4               6      16K  write        32       2       10
      4               6      16M   read        32       1        5
      4               6      16M  write        32       2       10
      4               6       1M   read        32       1        5
      4               6       1M  write        32       2       10
      4               6       2M   read        32       1        5
      4               6       2M  write        32       2       10
      4               8      16K   read        32       1        5
      4               8      16K  write         1       1        5
      4               8      16K  write        32       2       10
      4               8      16M   read        32       1        5
      4               8      16M  write         1       1        5
      4               8      16M  write        32       2       10
      4               8       1M   read        32       1        5
      4               8       1M  write         1       1        5
      4               8       1M  write        32       2       10
      4               8       2M   read        32       1        5
      4               8       2M  write         1       1        5
      4               8       2M  write        32       2       10
      4              12      16K  write         1       1        5
      4              12      16M  write         1       1        5
      4              12       1M  write         1       1        5
      4              12       2M  write         1       1        5
      4              16      16K   read        32       1        5
      4              16      16K  write        32       2       10
      4              16      16M   read        32       1        5
      4              16      16M  write        32       2       10
      4              16       1M   read        32       1        5
      4              16       1M  write        32       2       10
      4              16       2M   read        32       1        5
      4              16       2M  write        32       2       10
      4              24      16K  write         1       1        5
      4              24      16M  write         1       1        5
      4              24       1M  write         1       1        5
      4              24       2M  write         1       1        5
      4              32      16K   read        32       1        5
      4              32      16K  write         1       1        5
      4              32      16K  write        32       2       10
      4              32      16M   read        32       1        5
      4              32      16M  write         1       1        5
      4              32      16M  write        32       2       10
      4              32       1M   read        32       1        5
      4              32       1M  write         1       1        5
      4              32       1M  write        32       2       10
      4              32       2M   read        32       1        5
      4              32       2M  write         1       1        5
      4              32       2M  write        32       2       10
      4              48      16K   read        32       1        5
      4              48      16K  write         1       1        5
      4              48      16K  write        32       2       10
      4              48      16M   read        32       1        5
      4              48      16M  write         1       1        5
      4              48      16M  write        32       2       10
      4              48       1M   read        32       1        5
      4              48       1M  write         1       1        5
      4              48       1M  write        32       2       10
      4              48       2M   read        32       1        5
      4              48       2M  write         1       1        5
      4              48       2M  write        32       2       10
      4              96      16K  write         1       1        5
      4              96      16M  write         1       1        5
      4              96       1M  write         1       1        5
      4              96       2M  write         1       1        5
      4             108      16K  write         1       1        5
      4             108      16M  write         1       1        5
      4             108       1M  write         1       1        5
      4             108       2M  write         1       1        5
      4             128      16K  write         1       1        5
      4             128      16M  write         1       1        5

In [6]:
# --- Run-to-run variability: xfer 2M & 16M, segments=32, ppn in [8,16,32,48] ---
config_cols = ["nnodes", "tasks_per_node", "xfer_str", "access", "segments"]
display_cols = ["nnodes", "tasks_per_node", "xfer_str",
                "n_runs", "mean", "min", "max", "spread_GiB/s",
                "cv_within_pct", "cv_across"]

sub = all_df[
    all_df["xfer_str"].isin(["2M", "16M"]) &
    (all_df["segments"] == 32) &
    all_df["tasks_per_node"].isin([8, 16, 32, 48])
].copy()

# ── within-run CV ───────────────────────────────────────────────────────────
within = (
    sub.groupby(config_cols + ["experiment_run"])["bw(GiB/s)"]
    .agg(mean="mean", std="std")
    .assign(cv_within=lambda d: d["std"] / d["mean"] * 100)
    .reset_index()
    .groupby(config_cols)["cv_within"]
    .mean()
    .rename("cv_within_pct")
    .reset_index()
)

# ── across-run CV ───────────────────────────────────────────────────────────
run_means = (
    sub.groupby(config_cols + ["experiment_run"])["bw(GiB/s)"]
    .mean()
    .reset_index(name="run_mean")
)
across = (
    run_means.groupby(config_cols)["run_mean"]
    .agg(n_runs="count", mean="mean", std="std",
         min="min", max="max",
         cv_across=lambda x: x.std() / x.mean() * 100 if len(x) > 1 else float("nan"))
    .reset_index()
)

stats = across.merge(within, on=config_cols).sort_values(config_cols)
stats["spread_GiB/s"] = stats["max"] - stats["min"]

pd.set_option("display.float_format", "{:.1f}".format)
pd.set_option("display.max_rows", 200)

print("=== WRITE ===")
display(stats[stats["access"] == "write"][display_cols].reset_index(drop=True))

print("=== READ ===")
display(stats[stats["access"] == "read"][display_cols].reset_index(drop=True))

=== WRITE ===

,nnodes,tasks_per_node,xfer_str,n_runs,mean,min,max,spread_GiB/s,cv_within_pct,cv_across
0,1,8,16M,6,44.0,40.6,45.9,5.3,2.6,4.4
1,1,8,2M,6,21.2,18.4,22.1,3.7,4.8,6.6
2,1,16,16M,6,70.4,42.4,79.3,36.9,2.9,20.3
3,1,16,2M,6,38.1,22.2,44.3,22.1,5.3,22.3
4,1,32,16M,6,96.2,52.3,124.0,71.7,5.6,27.9
5,1,32,2M,6,60.6,27.9,78.5,50.6,4.4,34.4
6,1,48,16M,6,103.1,56.2,124.7,68.5,3.0,24.2
7,1,48,2M,6,80.3,31.5,100.5,69.0,4.0,34.5
8,2,8,16M,2,84.4,78.3,90.4,12.1,4.2,10.2
9,2,8,2M,2,40.3,38.6,42.0,3.4,4.3,6.0
10,2,16,16M,2,142.9,134.4,151.5,17.1,2.8,8.5
11,2,16,2M,2,65.0,45.7,84.3,38.6,39.6,42.0
12,2,32,16M,2,221.6,216.3,226.9,10.6,15.5,3.4
13,2,32,2M,2,151.1,144.8,157.4,12.6,6.7,5.9
14,2,48,16M,2,236.4,231.0,241.7,10.7,12.9,3.2
15,2,48,2M,2,195.5,192.4,198.5,6.1,4.8,2.2
16,4,8,16M,2,158.9,154.8,163.0,8.2,3.1,3.7
17,4,8,2M,2,82.6,80.1,85.1,5.0,4.1,4.3
18,4,16,16M,2,246.0,222.1,269.8,47.7,1.4,13.7
19,4,16,2M,2,156.6,151.4,161.7,10.4,10.7,4.7
20,4,32,16M,2,381.1,320.2,442.1,122.0,3.9,22.6
21,4,32,2M,2,271.9,239.7,304.2,64.5,6.9,16.8
22,4,48,16M,2,455.6,449.4,461.8,12.4,3.4,1.9
23,4,48,2M,2,330.5,290.7,370.3,79.6,8.1,17.0
24,8,8,16M,4,328.6,299.2,358.2,58.9,5.2,8.6
25,8,8,2M,4,176.9,160.7,190.6,29.9,7.9,8.2
26,8,16,16M,4,445.4,327.9,591.0,263.1,4.5,30.4
27,8,16,2M,4,261.2,214.4,308.6,94.2,8.8,19.7
28,8,32,16M,4,612.5,335.2,887.1,551.9,6.6,46.5
29,8,32,2M,4,380.5,204.2,543.1,338.8,10.0,49.1
30,8,48,16M,4,581.1,299.1,916.5,617.4,9.6,50.3
31,8,48,2M,4,457.1,217.6,694.2,476.6,11.4,50.9
32,16,8,16M,3,524.5,295.5,658.7,363.2,2.8,38.0
33,16,8,2M,3,283.8,175.3,338.1,162.7,8.4,33.1
34,16,16,16M,3,771.3,256.0,1079.7,823.7,8.2,58.2
35,16,16,2M,3,449.7,150.7,607.4,456.7,6.6,57.6
36,16,32,16M,3,1004.0,163.1,1478.6,1315.5,16.0,72.7
37,16,32,2M,3,648.3,118.2,966.8,848.7,24.8,71.3
38,16,48,16M,3,894.4,390.7,1492.8,1102.2,20.7,62.3
39,16,48,2M,3,719.0,200.2,1022.9,822.7,39.9,62.8
40,32,8,16M,2,738.6,245.3,1232.0,986.7,9.2,94.5
41,32,8,2M,2,392.9,88.5,697.4,608.9,43.8,109.6
42,32,16,16M,2,798.9,288.0,1309.9,1021.9,22.9,90.4
43,32,16,2M,2,442.3,235.0,649.6,414.6,22.2,66.3
44,32,32,16M,2,714.9,325.2,1104.6,779.4,30.3,77.1
45,32,32,2M,2,515.9,119.9,911.9,792.0,23.2,108.5
46,32,48,16M,2,1046.0,399.0,1693.0,1294.0,19.5,87.5
47,32,48,2M,2,409.2,163.8,654.5,490.7,23.6,84.8

=== READ ===

,nnodes,tasks_per_node,xfer_str,n_runs,mean,min,max,spread_GiB/s,cv_within_pct,cv_across
0,1,8,16M,1,58.1,58.1,58.1,0.0,1.7,NaN
1,1,8,2M,1,26.1,26.1,26.1,0.0,1.7,NaN
2,1,16,16M,1,41.2,41.2,41.2,0.0,6.3,NaN
3,1,16,2M,1,47.7,47.7,47.7,0.0,2.9,NaN
4,1,32,16M,1,30.9,30.9,30.9,0.0,4.0,NaN
5,1,32,2M,1,47.3,47.3,47.3,0.0,4.5,NaN
6,1,48,16M,1,32.7,32.7,32.7,0.0,6.8,NaN
7,1,48,2M,1,44.5,44.5,44.5,0.0,1.5,NaN
8,2,8,16M,1,114.8,114.8,114.8,0.0,2.1,NaN
9,2,8,2M,1,50.2,50.2,50.2,0.0,4.4,NaN
10,2,16,16M,1,69.2,69.2,69.2,0.0,10.2,NaN
11,2,16,2M,1,92.7,92.7,92.7,0.0,1.1,NaN
12,2,32,16M,1,53.3,53.3,53.3,0.0,5.3,NaN
13,2,32,2M,1,92.8,92.8,92.8,0.0,4.3,NaN
14,2,48,16M,1,54.6,54.6,54.6,0.0,7.5,NaN
15,2,48,2M,1,86.7,86.7,86.7,0.0,3.6,NaN
16,4,8,16M,1,213.0,213.0,213.0,0.0,2.6,NaN
17,4,8,2M,1,105.1,105.1,105.1,0.0,0.9,NaN
18,4,16,16M,1,117.7,117.7,117.7,0.0,15.2,NaN
19,4,16,2M,1,192.1,192.1,192.1,0.0,2.9,NaN
20,4,32,16M,1,87.8,87.8,87.8,0.0,8.1,NaN
21,4,32,2M,1,230.3,230.3,230.3,0.0,3.8,NaN
22,4,48,16M,1,99.3,99.3,99.3,0.0,16.3,NaN
23,4,48,2M,1,177.3,177.3,177.3,0.0,9.1,NaN
24,8,8,16M,2,368.0,311.3,424.8,113.5,1.8,21.8
25,8,8,2M,2,215.5,200.4,230.7,30.3,5.7,9.9
26,8,16,16M,2,258.1,177.1,339.0,161.9,8.7,44.4
27,8,16,2M,2,313.7,265.1,362.3,97.2,3.9,21.9
28,8,32,16M,2,208.7,146.7,270.7,124.0,13.7,42.0
29,8,32,2M,2,406.4,281.3,531.5,250.2,5.3,43.5
30,8,48,16M,2,297.7,177.9,417.6,239.7,10.7,56.9
31,8,48,2M,2,397.9,318.5,477.4,158.9,14.4,28.2
32,16,8,16M,1,855.9,855.9,855.9,0.0,1.5,NaN
33,16,8,2M,1,437.4,437.4,437.4,0.0,0.5,NaN
34,16,16,16M,1,443.8,443.8,443.8,0.0,31.1,NaN
35,16,16,2M,1,759.8,759.8,759.8,0.0,7.2,NaN
36,16,32,16M,1,237.6,237.6,237.6,0.0,19.0,NaN
37,16,32,2M,1,1046.0,1046.0,1046.0,0.0,10.5,NaN
38,16,48,16M,1,265.4,265.4,265.4,0.0,2.8,NaN
39,16,48,2M,1,1030.2,1030.2,1030.2,0.0,9.8,NaN
40,32,8,16M,1,1574.4,1574.4,1574.4,0.0,4.0,NaN
41,32,8,2M,1,846.9,846.9,846.9,0.0,6.7,NaN
42,32,16,16M,1,1427.7,1427.7,1427.7,0.0,39.5,NaN
43,32,16,2M,1,1313.8,1313.8,1313.8,0.0,14.0,NaN
44,32,32,16M,1,450.5,450.5,450.5,0.0,7.7,NaN
45,32,32,2M,1,1541.3,1541.3,1541.3,0.0,20.3,NaN
46,32,48,16M,1,519.6,519.6,519.6,0.0,5.1,NaN
47,32,48,2M,1,1602.0,1602.0,1602.0,0.0,28.7,NaN

In [7]:
# --- Within-run stability (iter-to-iter CV per run) ---
within_detail = (
    sub.groupby(config_cols + ["experiment_run"])["bw(GiB/s)"]
    .agg(mean="mean", std="std", n_iters="count")
    .assign(cv_within=lambda d: d["std"] / d["mean"] * 100)
    .reset_index()
)

pd.set_option("display.float_format", "{:.1f}".format)
for acc in ["write", "read"]:
    t = within_detail[within_detail["access"] == acc]["cv_within"]
    print(f"=== {acc.upper()} — cv_within per run ({len(t)} runs) ===")
    print(t.describe().rename({
        "count": "n_runs", "mean": "mean_cv", "std": "std_cv",
        "min": "min_cv", "25%": "Q1", "50%": "median", "75%": "Q3", "max": "max_cv"
    }).to_string())
    print(f"  cv > 10% : {(t > 10).sum()} runs ({(t > 10).mean()*100:.0f}%)")
    print(f"  cv > 20% : {(t > 20).sum()} runs ({(t > 20).mean()*100:.0f}%)")
    print()

    worst = (
        within_detail[within_detail["access"] == acc]
        .nlargest(8, "cv_within")
        [["nnodes", "tasks_per_node", "xfer_str", "experiment_run", "n_iters", "mean", "cv_within"]]
    )
    print(f"  Worst 8 runs by cv_within:")
    display(worst.reset_index(drop=True))
    print()

=== WRITE — cv_within per run (152 runs) ===
n_runs    152.0
mean_cv     9.8
std_cv     12.0
min_cv      0.7
Q1          3.2
median      5.6
Q3         11.0
max_cv     74.9
  cv > 10% : 43 runs (28%)
  cv > 20% : 18 runs (12%)

  Worst 8 runs by cv_within:

,nnodes,tasks_per_node,xfer_str,experiment_run,n_iters,mean,cv_within
0,32,8,2M,ior-results-w_n-32_seg-32_8304643,5,88.5,74.9
1,2,16,2M,ior-results-w_n-2_seg-32_8305889,5,45.7,72.7
2,16,48,2M,ior-results-w_n-16_seg-32_8304613,5,200.2,50.8
3,32,32,16M,ior-results-rw_n-32_seg-32_8378205,5,1104.6,44.6
4,16,32,2M,ior-results-w_n-16_seg-32_8304613,5,118.2,43.7
5,32,48,2M,ior-results-rw_n-32_seg-32_8378205,3,654.5,42.3
6,16,48,2M,ior-results-w_n-16_seg-32_20251017_48core-skip1,5,933.9,35.8
7,32,32,2M,ior-results-rw_n-32_seg-32_8378205,5,911.9,34.6

=== READ — cv_within per run (56 runs) ===
n_runs    56.0
mean_cv    8.3
std_cv     7.8
min_cv     0.5
Q1         2.9
median     6.3
Q3        10.2
max_cv    39.5
  cv > 10% : 15 runs (27%)
  cv > 20% : 4 runs (7%)

  Worst 8 runs by cv_within:

,nnodes,tasks_per_node,xfer_str,experiment_run,n_iters,mean,cv_within
0,32,16,16M,ior-results-rw_n-32_seg-32_8378205,5,1427.7,39.5
1,16,16,16M,ior-results-rw_n-16_seg-32_8340995,5,443.8,31.1
2,32,48,2M,ior-results-rw_n-32_seg-32_8378205,3,1602.0,28.7
3,32,32,2M,ior-results-rw_n-32_seg-32_8378205,5,1541.3,20.3
4,16,32,16M,ior-results-rw_n-16_seg-32_8340995,5,237.6,19.0
5,8,32,16M,ior-results-rw_n-8_seg-32_8305849,5,146.7,17.9
6,4,48,16M,ior-results-rw_n-4_seg-32_8330848,5,99.3,16.3
7,4,16,16M,ior-results-rw_n-4_seg-32_8330848,5,117.7,15.2

### Run-to-run variability: xfer 2 MiB & 16 MiB (seg=32, ppn 8/16/32/48)

Two levels of variance are reported:
- **`cv_within_pct`** — CV (std/mean × 100%) across the 5 iterations *within* a single run. Reflects measurement noise inside one job submission.
- **`cv_across`** — CV of per-run means across independent job submissions. Reflects true run-to-run reproducibility (NaN when only one run exists).

#### Within-run stability (iter-to-iter)

**Write (152 individual runs):**
- Median `cv_within` = 5.6% — the typical run is reasonably stable.
- But 43 / 152 runs (28%) exceed 10%, and 18 / 152 (12%) exceed 20%.
- The worst offenders are concentrated at large node counts: n=32/ppn=8/2M reaches 75%, n=2/ppn=16/2M reaches 73%, and several n=16/n=32 runs exceed 30–50%.
- Small configs (n ≤ 4) are consistently stable within a run (cv_within < 10%).

**Read (56 individual runs):**
- Median `cv_within` = 6.3% — similar to write overall.
- 15 / 56 runs (27%) exceed 10%, 4 / 56 (7%) exceed 20%.
- Worst cases: n=32/ppn=16/16M (40%), n=16/ppn=16/16M (31%), n=32/ppn=48/2M (29%).
- Again, instability is driven by large node counts; small configs are stable.

**Overall:** Within-run stability is *not* uniformly good. The 5 iterations within a single run can vary substantially at n ≥ 16, meaning even a single run's mean is an unreliable summary for those configs.

#### Across-run variability (run-to-run)

##### Write (48 configs — all have ≥ 2 runs)

| Nodes | `cv_across` range | Notes |
|------:|------------------:|-------|
| 1     | 4–35%             | ppn=8 stable (4–7%); variability increases with ppn |
| 2     | 2–42%             | Mostly stable; n=2/ppn=16/2M outlier (42%) |
| 4     | 2–23%             | Stable at ppn=8/48; n=4/ppn=32 reaches 23% |
| 8     | 8–51%             | ppn=8 stable (8–9%); ppn=32/48 highly variable (47–51%) |
| 16    | 33–73%            | Highly unstable across all ppn — 2–4× swings between runs |
| 32    | 66–110%           | Extremely unstable — bandwidth can differ by ~10× between runs |

##### Read (48 configs — mostly single-run)

- **n=1 to n=4:** Only 1 run per config — `cv_across` unavailable. Within-run CV is low (< 10%).
- **n=8:** 2 runs; `cv_across` ranges 10–57%. ppn=8 is most stable (~10%); ppn=32/48 reach 43–57%.
- **n=16 and n=32:** Only 1 run per config — reproducibility unknown. Within-run CV can be high (up to 40% for n=32/ppn=16/16M).

#### Summary

Neither within-run nor across-run stability can be assumed at large node counts (n ≥ 16). The 5 iterations inside a single run already show large swings, and independent job submissions diverge even more. Reliable conclusions require multiple runs at n ≥ 8 with high ppn, and especially at n ≥ 16.